services:
  mysql:
    image: mysql:8.0
    container_name: pokemon-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --default-time-zone=-05:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pokemon_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: pokemon-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: 3001
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      CORS_ORIGINS: ${CORS_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_EXPIRES_IN: ${REFRESH_EXPIRES_IN}
    networks:
      - pokemon_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.pokemon-api.rule=Host(`pokemonapi.globtecx.com`)"
      - "traefik.http.routers.pokemon-api.entrypoints=websecure"
      - "traefik.http.routers.pokemon-api.tls=true"
      - "traefik.http.routers.pokemon-api.tls.certresolver=le"

      - "traefik.http.services.pokemon-api.loadbalancer.server.port=3001"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    container_name: pokemon-frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    networks:
      - pokemon_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.pokemon-app.rule=Host(`pokemonapp.globtecx.com`)"
      - "traefik.http.routers.pokemon-app.entrypoints=websecure"
      - "traefik.http.routers.pokemon-app.tls=true"
      - "traefik.http.routers.pokemon-app.tls.certresolver=le"

      - "traefik.http.services.pokemon-app.loadbalancer.server.port=3000"

volumes:
  mysql_data:

networks:
  pokemon_net:
    driver: bridge
  proxy:
    external: true
